### ISSUE TITLE
Permission write secure settings problem

### ISSUE THREAD

**Issue by Algarues** [flxapps/DetoxDroid#108]
The app has been granted permission to write secure settings. It is indicates in app managers and in Permission manager X.
However when the app is activated it complaints that the permission is not granted.

On Oneui 6

**Comment by flxapps** [comment]
This should be fixed by now.
@Algarues Can you confirm?

**Comment by Algarues** [comment]
Now it works
However, when i activate the automatic grayscale i see that also the system colour correction becomes activated in the quick tiles.

What happens is also that the apps added to the exceptions still appear in grayscale when opened
